name: wildrun
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  flame_audio: ^2.10.0
  hive: ^2.2.3 
  path_provider: ^2.1.2 
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/brand/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/brand/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/brand/icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/brand/
    - assets/images/parallax/
    - assets/images/animals/
    - assets/images/enemies/
    - assets/images/landscape/
    - assets/images/items/
    - assets/images/effects/
    - assets/images/tutos/
    - assets/images/players/player1/
    - assets/audio/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: Oswald-regular
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
      
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700